resources:
  containers:
  - container: mynginx
    image: nginx:latest
steps:
- script: echo "I can run inside the container (it starts by default)"
  target:
    container: mynginx
- task: Docker@2
  inputs:
    command: stop
    container: mynginx
# any task beyond this point would not be able to target the mynginx container
# because it's been stopped